name: 部署静态页面

on:
  push:
    branches:
      - main
      - master
#     paths:
#       - "plugins/**"
#       - "tiddlers/**"
#       - "package.json"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Cache dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: 安装 NodeJS 依赖
        run: npm install -g pnpm && pnpm install

      # - name: 运行zx构建
      #   run: npm run zx-build

      - name: 构建静态网页
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Upload entire repository
          path: ./public
      - name: 部署到GitHub页面
        id: deployment
        uses: actions/deploy-pages@v4.0.5
